services:
    auto-rsa:
        container_name: auto-rsa
        image: docker.io/nelsondane/auto-rsa:latest@sha256:bed295bbe9b2616ed230bcfcd519465226d63eaa6ab7d1fbda90858c5ae87c99 # or change to other branch you want to use
        # build: . # uncomment this line if you want to build the image locally with "docker compose up -d --build"
        restart: unless-stopped
        env_file:
            - .env
        tty: true
        volumes:
            - ./creds:/app/creds

    watchtower:
        # Auto update the auto-rsa container every hour
        # For more info see: https://containrrr.dev/watchtower/arguments/
        image: containrrr/watchtower@sha256:6dd50763bbd632a83cb154d5451700530d1e44200b268a4e9488fefdfcf2b038
        container_name: watchtower
        hostname: auto-rsa
        environment:
            - WATCHTOWER_CLEANUP=true
            - WATCHTOWER_INCLUDE_STOPPED=true
            - WATCHTOWER_POLL_INTERVAL=3600
            # For more info on notifications see: https://containrrr.dev/watchtower/notifications/
            # - WATCHTOWER_NOTIFICATIONS=shoutrrr
            # - WATCHTOWER_NOTIFICATION_URL=discord://TOKEN@WEBHOOKID
        command:
            - auto-rsa
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart: unless-stopped
