[project]
name = "auto_rsa_bot"
version = "2.2.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bbae-invest-api==0.1.5",
    "chaseinvest-api==0.4.7",
    "curl-cffi>=0.16.2",
    "discord-py==2.7.1",
    "dspac-invest-api==0.1.4",
    "email-validator>=2.3.0",
    "fennel-invest-api==2.0.1",
    "fidelity-api==0.0.17",
    "firstrade==0.0.39",
    "nodriver>=0.47.0",
    "publicdotcom-py==0.1.22",
    "pyotp>=2.10.0",
    "python-dotenv>=1.2.3",
    "robin_stocks@git+https://github.com/NelsonDane/robin_stocks_v2@1ba446970f7bac5c4c0ac96390ae9e3f7a9b9d0e",
    "requests>=2.34.2",
    "schwab-api2==0.3.0",
    "selenium>=4.38.0",
    "selenium-stealth>=1.0.6",
    "tastytrade==13.2.3",
    "typer>=0.20.0",
    "vanguard-api==0.3.3",
    "webull@git+https://github.com/NelsonDane/webull@ef14ae63f9e1436fbea77fe864df54847cf2f730",
]

[dependency-groups]
dev = [
    "deptry>=0.25.1",
    "ruff>=0.13.3",
    "ty>=0.0.11",
    "types-requests>=2.32.4.20250913",
    "vulture>=2.16",
]

[project.scripts]
auto_rsa_bot = "src.cli:app"
auto-rsa-bot = "src.cli:app"

[tool.uv]
package = true

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "src"
module-root = "."

[tool.ruff]
target-version = "py312"
extend = "./styles/ruff.toml"
include = ["src/*"]
exclude = ["docs/*"]

[tool.ruff.lint]
ignore = [
    "BLE001",  # Allow blind exception catch
    "T201",    # Allow prints
    "TRY002",  # Create own exception
    "TRY301",  # Allow raising exceptions
    "DOC201",  # Don't require returns in doc
    "DOC501",  # Don't require raises in doc
]
[tool.ruff.lint.per-file-ignores]
"src/brokerages/*" = [
    "PLR0913", # Allow too many arguments
    "PLR1702", # Allow many nested blocks
]

[tool.ty.environment]
root = ["src"]
python-version = "3.12"

[tool.ty.src]
exclude = ["docs/*", "vulture_whitelist.py"]

[tool.deptry]
exclude = [
    "docs",
    ".venv",
    "tests",
    "vulture_whitelist.py"
]

[tool.vulture]
min_confidence = 60
paths = ["src", "vulture_whitelist.py"]
